name: C/C++ CI

on: [push]

jobs:
  check-and-build-tinymovr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install cppcheck
      run: git clone https://github.com/danmar/cppcheck.git; cd cppcheck; mkdir build; cd build; cmake -B. ..; sudo make install
      working-directory: firmware
    - name: Run cppcheck on Tinymovr
      run: cppcheck --force --addon=cert --addon=misra --error-exitcode=1 -isrc/utils -isrc/nvm -isrc/uart -isrc/can -isrc/adc src
      working-directory: firmware
    - name: Remove cppcheck
      run: rm -rf ./cppcheck
      working-directory: firmware
    # - name: Install gcc-arm-none-eabi
    #   run: sudo apt install gcc-arm-none-eabi
    #   working-directory: firmware
    # - name: Build Tinymovr
    #   run: make
    #   working-directory: firmware