name: Tinymovr Studio Test with Tox

on: [push]

env:  # Define the environment variables for this step
  TEST_PYPI_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
  TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}

jobs:
  test-studio-tox:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run:  |
        cd studio/Python
        tox


        